# This file tells Travis CI how to build and run your tests
# Hopefull, this will work
language: cpp
compiler:
    - g++
before_script:
    - sudo apt-get install libgtest-dev
script: "make test"
branches:
    only:
        - master
