# This file tells Travis CI how to build and run your tests
# Hopefull, this will work
language: cpp
compiler:
    - g++
before_script:
    - pwd
    - export OLD_DIRECTORY=pwd
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo mv libg* /usr/lib/
    - cd $OLD_DIRECTORY
script: "make test"
branches:
    only:
        - master
